disabled_rules:
  - force_cast
  - force_try
  - nesting
  - trailing_whitespace
  - large_tuple

opt_in_rules:
  - vertical_parameter_alignment_on_call
  - unowned_variable_capture
  - operator_usage_whitespace
  - multiline_parameters_brackets
  - empty_collection_literal
  - closure_spacing
  - anyobject_protocol
  - identical_operands

type_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]

identifier_name:
  min_length:
    warning: 1
  max_length:
    error: 40

line_length: 192

function_body_length:
  warning: 48
  error: 64

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

excluded:
  - .build
