line_length: 180

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

type_body_length:
  warning: 200
  error: 400

file_length:
  warning: 400
  error: 800

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length:
    warning: 1
  max_length:
    error: 40

